- hosts: all
  become: yes
  tasks:
  - name: Title 1
    shell: echo "The machine kernel is as follows:" >> maintenance_test1.txt
  - name: Machine Kernel
    shell: uname -a >> maintenance_test1.txt
  - name: Title 2
    shell: echo "The machine filesystem is as follows:" >> maintenance_test1.txt
  - name: Machine Kernel
    shell: df -h >> maintenance_test1.txt
	