- hosts: all
  become: yes
  tasks:
  - name: Title 1
    shell: echo "Hostname of this machine is:" >> maintenance_test1.txt
  - name: Hostname
    shell: echo $HOSTNAME >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 2
    shell: echo "The Red Hat Release as follows:" >> maintenance_test1.txt
  - name: Red Hat version
    shell: cat /etc/redhat-release >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 3
    shell: echo "The machine kernel is as follows:" >> maintenance_test1.txt
  - name: Machine Kernel
    shell: uname -a >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 4
    shell: echo "The system is working without reboot for:" >> maintenance_test1.txt
  - name: Uptime
    shell: uptime >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 5
    shell: echo "The network configuration of this machine is:" >> maintenance_test1.txt
  - name: Network Configuration
    shell: ifconfig >> maintenance_test1.txt
  - name: Continue
    shell: cat /etc/sysconfig/network >> maintenance_test1.txt
  - name: Continue
    shell: cat /etc/sysconfig/network-scripts/ifcfg-ens* >> maintenance_test1.txt
  - name: Continue
    shell: netstat -r >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 6
    shell: echo "The /etc/hosts file is as follows:" >> maintenance_test1.txt
  - name: Hosts
    shell: cat /etc/hosts >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 7
    shell: echo "The DNS servers are as follows:" >> maintenance_test1.txt
  - name: DNS
    shell: cat /etc/resolv.conf >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 8
    shell: echo "The iomem of this machine is as follows:" >> maintenance_test1.txt
  - name: IOMEM
    shell: cat /proc/iomem >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 9
    shell: echo "The ioports of this machine is as follows:" >> maintenance_test1.txt
  - name: IOPORTS
    shell: cat /proc/ioports >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 10
    shell: echo "The Interrupts of this machine are as follows:" >> maintenance_test1.txt
  - name: INTERRUPTS
    shell: cat /proc/interrupts >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 11
    shell: echo "The number of CPUs together with the CPU family of this machine are:" >> maintenance_test1.txt
  - name: CPU
    shell: cat /proc/cpuinfo >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 12
    shell: echo "The CPU utilization of this machine is:" >> maintenance_test1.txt
  - name: CPU Utilization
    shell: iostat -c -t >> maintenance_test1.txt
  - name: sleep
    shell: sleep 10
  - name: continue
    shell: iostat -c -t >> maintenance_test1.txt
  - name: sleep
    shell: sleep 10
  - name: continue
    shell: iostat -c -t >> maintenance_test1.txt
  - name: sleep
    shell: sleep 10
  - name: continue
    shell: iostat -c -t >> maintenance_test1.txt
  - name: sleep
    shell: sleep 10
  - name: continue
    shell: iostat -c -t >> maintenance_test1.txt
  - name: sleep
    shell: sleep 10
  - name: continue
    shell: iostat -c -t >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 13
    shell: echo "Physical Partitions Created:" >> maintenance_test1.txt
  - name: Physical Partitions
    shell: fdisk -l >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 14
    shell: echo "Hard Drives utilization:" >> maintenance_test1.txt
  - name: Hard Drives Utilization
    shell: df -h >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 15
    shell: echo "Review Physical Volumes, Volume Groups and Logical Volumes:" >> maintenance_test1.txt
  - name: Physical Volumes, Volume Groups and Logical Volumes
    shell: pvdisplay >> maintenance_test1.txt && vgdisplay >> maintenance_test1.txt && lvdisplay >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 16
    shell: echo "The i/o of h/d is as follows:" >> maintenance_test1.txt
  - name: I/O of H/D
    shell: iostat -d -k -t >> maintenance_test1.txt && sleep 10 && iostat -d -k -t >> maintenance_test1.txt && sleep 10 && iostat -d -k -t >> maintenance_test1.txt && sleep 10 && iostat -d -k -t >> maintenance_test1.txt && sleep 10 && iostat -d -k -t >> maintenance_test1.txt && sleep 10 && iostat -d -k -t >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 17
    shell: echo "Memory utilization:" >> maintenance_test1.txt
  - name: Memory utilization
    shell: cat /proc/meminfo >> maintenance_test1.txt && free >> maintenance_test1.txt && vmstat >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 18
    shell: echo "Network ports monitoring for localhost:" >> maintenance_test1.txt
  - name: Network ports
    shell: nmap localhost >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 19
    shell: echo "Network ports monitoring for $HOSTNAME:" >> maintenance_test1.txt
  - name: Network ports HOSTNAME
    shell: nmap $HOSTNAME >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 20
    shell: echo "Monitor ports and services LISTENING:" >> maintenance_test1.txt
  - name: Ports and services
    shell: netstat -ntaupe >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 21
    shell: echo "Monitor system services runlevel status:" >> maintenance_test1.txt
  - name: System Services
    shell: chkconfig --list >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 22
    shell: echo "Monitor system services current status:" >> maintenance_test1.txt
  - name: System Services current status
    shell: service --status-all >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 23
    shell: echo "Local system users are as follows:" >> maintenance_test1.txt
  - name: Local system users
    shell: cat /etc/passwd >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 24
    shell: echo "Local system groups are as follows:" >> maintenance_test1.txt
  - name: Local system groups
    shell: cat /etc/group >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 25
    shell: echo "Find latest system logins:" >> maintenance_test1.txt
  - name: Latest system logins
    shell: last >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 26
    shell: echo "Unique latest system logins:" >> maintenance_test1.txt
  - name: Latest system logins unique
    shell: last > /tmp/tt && cut -c 23-38 /tmp/tt | sort | uniq >> maintenance_test1.txt