- hosts: all
  become: yes
  tasks:
  - name: Title 1
    shell: echo "Hostname of this machine is:" >> maintenance_test1.txt
  - name: Hostname
    shell: echo $HOSTNAME >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 2
    shell: echo "The Red Hat Release as follows:" >> maintenance_test1.txt
  - name: Red Hat version
    shell: cat /etc/redhat-release >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 3
    shell: echo "The machine kernel is as follows:" >> maintenance_test1.txt
  - name: Machine Kernel
    shell: uname -a >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 4
    shell: echo "The system is working without reboot for:" >> maintenance_test1.txt
  - name: Uptime
    shell: uptime >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 5
    shell: echo "The network configuration of this machine is:" >> maintenance_test1.txt
  - name: Network Configuration
    shell: ifconfig >> maintenance_test1.txt
  - name: Continue
    shell: cat /etc/sysconfig/network >> maintenance_test1.txt
  - name: Continue
    shell: cat /etc/sysconfig/network-scripts/ifcfg-ens* >> maintenance_test1.txt
  - name: Continue
    shell: netstat -r >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 6
    shell: echo "The /etc/hosts file is as follows:" >> maintenance_test1.txt
  - name: Hosts
    shell: cat /etc/hosts >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 7
    shell: echo "The DNS servers are as follows:" >> maintenance_test1.txt
  - name: DNS
    shell: cat /etc/resolv.conf >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 8
    shell: echo "The iomem of this machine is as follows:" >> maintenance_test1.txt
  - name: IOMEM
    shell: cat /proc/iomem >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 9
    shell: echo "The ioports of this machine is as follows:" >> maintenance_test1.txt
  - name: IOPORTS
    shell: cat /proc/ioports >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 10
    shell: echo "The Interrupts of this machine are as follows:" >> maintenance_test1.txt
  - name: INTERRUPTS
    shell: cat /proc/interrupts >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 11
    shell: echo "The number of CPUs together with the CPU family of this machine are:" >> maintenance_test1.txt
  - name: CPU
    shell: cat /proc/cpuinfo >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 12
    shell: echo "The CPU utilization of this machine is:" >> maintenance_test1.txt
  - name: CPU Utilization
    shell: iostat -c -t >> maintenance_test1.txt
  - name: sleep
    shell: sleep 10
  - name: continue
    shell: iostat -c -t >> maintenance_test1.txt
  - name: sleep
    shell: sleep 10
  - name: continue
    shell: iostat -c -t >> maintenance_test1.txt
  - name: sleep
    shell: sleep 10
  - name: continue
    shell: iostat -c -t >> maintenance_test1.txt
  - name: sleep
    shell: sleep 10
  - name: continue
    shell: iostat -c -t >> maintenance_test1.txt
  - name: sleep
    shell: sleep 10
  - name: continue
    shell: iostat -c -t >> maintenance_test1.txt