- hosts: all
  become: yes
  tasks:
  - name: Title 1
    shell: echo "Hostname of this machine is:" >> maintenance_test1.txt
  - name: Hostname
    shell: echo $HOSTNAME >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 2
    shell: echo "The Red Hat Release as follows:" >> maintenance_test1.txt
  - name: Red Hat version
    shell: cat /etc/redhat-release >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 3
    shell: echo "The machine kernel is as follows:" >> maintenance_test1.txt
  - name: Machine Kernel
    shell: uname -a >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 4
    shell: echo "The system is working without reboot for:" >> maintenance_test1.txt
  - name: Uptime
    shell: uptime >> maintenance_test1.txt
  - name: Line Break
    shell: echo "--------------------------------------------------------------------------------" >> maintenance_test1.txt
  - name: Title 5
    shell: echo "The network configuration of this machine is:" >> maintenance_test1.txt
  - name: Network Configuration
    shell: ifconfig >> maintenance_test1.txt
  - name: Continue
    shell: cat /etc/sysconfig/network >> maintenance_test1.txt
  - name: Continue
    shell: cat /etc/sysconfig/network-scripts/ifcfg-ens* >> maintenance_test1.txt
  - name: Continue
    shell: netstat -r >> maintenance_test1.txt